---
dependencies: [] 

galaxy_info:
  author: Sagar
  description: Ruby installation for Ubuntu.
  company: "INITCRON SYSTEMS pvt. ltd."
  license: "license (BSD, MIT)"
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
      - all
    - name: GenericUNIX
      versions:
      - all
    - name: Fedora
      versions:
      - all
    - name: opensuse
      versions:
      - all
    - name: GenericBSD
      versions:
      - all
    - name: FreeBSD
      versions:
      - all
    - name: Ubuntu
      versions:
      - lucid
      - trusty
      - precise
    - name: SLES
      versions:
      - all
    - name: GenericLinux
      versions:
      - all
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - development
    - web
